{
  "adaptive_noise_scale": 0,
  "additional_parameters": "",
  "ae": "",
  "apply_t5_attn_mask": false,
  "async_upload": false,
  "batch_size": "1",
  "block_lr": "",
  "blocks_to_swap": 0,
  "blockwise_fused_optimizers": false,
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "cache_latents": true,
  "cache_latents_to_disk": true,
  "caption_dropout_every_n_epochs": 0,
  "caption_dropout_rate": 0,
  "caption_extension": ".txt",
  "caption_metadata_filename": "/root/lanyun-tmp/data_test/meta_cap.json",
  "clip_g": "",
  "clip_l": 0,
  "clip_skip": 1,
  "color_aug": false,
  "cpu_offload_checkpointing": false,
  "create_buckets": true,
  "create_caption": true,
  "dataset_config": "",
  "dataset_repeats": "1",
  "debiased_estimation_loss": false,
  "disable_mmap_load_safetensors": false,
  "discrete_flow_shift": 3,
  "double_blocks_to_swap": 0,
  "dynamo_backend": "no",
  "dynamo_mode": "default",
  "dynamo_use_dynamic": false,
  "dynamo_use_fullgraph": false,
  "epoch": 1,
  "extra_accelerate_launch_args": "",
  "flip_aug": false,
  "flux1_cache_text_encoder_outputs": false,
  "flux1_cache_text_encoder_outputs_to_disk": false,
  "flux1_checkbox": false,
  "flux1_clip_l": "",
  "flux1_t5xxl": "",
  "flux_fused_backward_pass": false,
  "fp8_base": false,
  "full_bf16": true,
  "full_fp16": false,
  "full_path": true,
  "fused_backward_pass": false,
  "fused_optimizer_groups": 0,
  "gpu_ids": "0,1,2,3",
  "gradient_accumulation_steps": 1,
  "gradient_checkpointing": true,
  "guidance_scale": 3.5,
  "huber_c": 0.1,
  "huber_scale": 1,
  "huber_schedule": "snr",
  "huggingface_path_in_repo": "",
  "huggingface_repo_id": "",
  "huggingface_repo_type": "",
  "huggingface_repo_visibility": "",
  "huggingface_token": "",
  "image_folder": "/root/lanyun-tmp/data_test/1_evernight_nai2",
  "ip_noise_gamma": 0,
  "ip_noise_gamma_random_strength": false,
  "keep_tokens": 0,
  "latent_metadata_filename": "",
  "learning_rate": 1e-05,
  "learning_rate_te": 1e-05,
  "learning_rate_te1": 1e-05,
  "learning_rate_te2": 1e-05,
  "log_config": false,
  "log_tracker_config": "",
  "log_tracker_name": "",
  "log_with": "",
  "logging_dir": "",
  "logit_mean": 1,
  "logit_std": 1.29,
  "loss_type": "l2",
  "lr_scheduler": "constant",
  "lr_scheduler_args": "",
  "lr_scheduler_type": "",
  "lr_warmup": 0,
  "lr_warmup_steps": 0,
  "main_process_port": 7860,
  "masked_loss": false,
  "max_bucket_reso": "1024",
  "max_data_loader_n_workers": 0,
  "max_resolution": "1024,1024",
  "max_timestep": 1000,
  "max_token_length": 75,
  "max_train_epochs": 5,
  "max_train_steps": 0,
  "mem_eff_attn": false,
  "mem_eff_save": false,
  "metadata_author": "",
  "metadata_description": "",
  "metadata_license": "",
  "metadata_tags": "",
  "metadata_title": "",
  "min_bucket_reso": "256",
  "min_snr_gamma": 0,
  "min_timestep": 0,
  "mixed_precision": "bf16",
  "mode_scale": false,
  "model_list": "custom",
  "model_prediction_type": "sigma_scaled",
  "multi_gpu": true,
  "multires_noise_discount": 0.3,
  "multires_noise_iterations": 0,
  "noise_offset": 0,
  "noise_offset_random_strength": false,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 10,
  "num_machines": 1,
  "num_processes": 4,
  "optimizer": "PagedAdamW8bit",
  "optimizer_args": "",
  "output_dir": "/root/lanyun-tmp/output/test_0910_fn",
  "output_name": "test_0910_fn",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "/root/lanyun-tmp/model/200w_noache.safetensors",
  "random_crop": false,
  "resume": "",
  "resume_from_huggingface": "",
  "sample_every_n_epochs": 0,
  "sample_every_n_steps": 0,
  "sample_prompts": "",
  "sample_sampler": "euler_a",
  "save_as_bool": false,
  "save_clip": false,
  "save_every_n_epochs": 5,
  "save_every_n_steps": 0,
  "save_last_n_epochs": 0,
  "save_last_n_epochs_state": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "fp16",
  "save_state": false,
  "save_state_on_train_end": false,
  "save_state_to_huggingface": false,
  "save_t5xxl": "",
  "scale_v_pred_loss_like_noise_pred": false,
  "sd3_cache_text_encoder_outputs": false,
  "sd3_cache_text_encoder_outputs_to_disk": false,
  "sd3_checkbox": false,
  "sd3_fused_backward_pass": "",
  "sd3_text_encoder_batch_size": false,
  "sdxl_cache_text_encoder_outputs": false,
  "sdxl_checkbox": false,
  "sdxl_no_half_vae": false,
  "seed": 0,
  "shuffle_caption": false,
  "single_blocks_to_swap": 0,
  "skip_cache_check": false,
  "split_mode": false,
  "t5xxl": "",
  "t5xxl_device": "bf16",
  "t5xxl_dtype": 1,
  "t5xxl_max_token_length": 512,
  "timestep_sampling": "sigma",
  "train_batch_size": 16,
  "train_blocks": "all",
  "train_dir": "",
  "train_text_encoder": false,
  "use_latent_files": "No",
  "v2": false,
  "v_parameterization": false,
  "v_pred_like_loss": 0,
  "vae_batch_size": 0,
  "wandb_api_key": "",
  "wandb_run_name": "",
  "weighted_captions": false,
  "weighting_scheme": "logit_normal",
  "xformers": "xformers"
}