model_train_type = "anima-lora"
pretrained_model_name_or_path = "./sd-models/anima/anima-base-v1.0.safetensors"
vae = "./sd-models/anima/qwen_image_vae.safetensors"
qwen3 = "./sd-models/anima/qwen_3_06b_base.safetensors"
qwen3_max_token_length = 512
t5_max_token_length = 512
timestep_sampling = "shift"
sigmoid_scale = 1
discrete_flow_shift = 3
weighting_scheme = "uniform"
attn_mode = ""
split_attn = false
vae_disable_cache = false
unsloth_offload_checkpointing = false
train_data_dir = "D:/ai/lora-scripts-next/data/xinhaicheng"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = "xin"
output_dir = "./output/xin"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 1
save_state = false
max_train_epochs = 20
train_batch_size = 1
gradient_checkpointing = true
gradient_accumulation_steps = 1
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0001
text_encoder_lr = 0.00001
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdamW8bit"
lora_type = "lora"
network_dim = 16
network_alpha = 16
dim_from_weights = false
network_module = "networks.lora_anima"
pissa_init = false
positive_prompts = "1girl, solo, smile, japanese clothes, kimono, blue eyes, closed mouth, upper body, looking at viewer, hair ornament, long hair, yellow kimono, black hair, anime coloring, yukata, choker, split mouth, side ponytail, bow, brown hair"
negative_prompts = "nsfw, explicit, sexual content, nude, naked, nipples, areola, genitals, cleavage, breasts, ass, buttocks, thighs, underwear, lingerie, bikini, swimsuit, erotic, suggestive, lewd, spread legs, close-up body, transparent clothes, worst quality, low quality, score_1, score_2, score_3, artist name, jpeg artifacts"
sample_width = 1024
sample_height = 1024
sample_cfg = 4.5
sample_seed = 42
sample_steps = 40
sample_sampler = "euler"
sample_scheduler = "simple"
sample_at_first = true
sample_every_n_epochs = 2
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 0
prefer_json_caption = true
seed = 1337
clip_skip = 2
mixed_precision = "bf16"
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
persistent_data_loader_workers = false
fp8_base = false
fp8_base_unet = false
max_data_loader_n_workers = 0
disable_mmap_load_safetensors = false
cpu_offload_checkpointing = false
enable_debug_options = false
